CREATE TABLE MEMBER(
    NAME VARCHAR2(20) NOT NULL,
    ID VARCHAR2(10) PRIMARY KEY,
    PW VARCHAR2(20) NOT NULL,
    COUPON NUMBER(1),
    AUTH NUMBER(1) NOT NULL,
    ADR VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL
);

CREATE TABLE MENU(
    MENU_NAME VARCHAR2(15) PRIMARY KEY,
    PRICE NUMBER(5) NOT NULL
);

CREATE TABLE ORDER_DETAIL(
    ID VARCHAR2(10),
    MENU_NAME VARCHAR2(15),
    COUNT1 NUMBER(10) NOT NULL,
    BEV_COUPON NUMBER(10),
    REVIEW VARCHAR2(1000),
    SCORE NUMBER(5),

);

SELECT ID ,PW  FROM MEMBER  WHERE ID = '55' AND PW = '5' 

SELECT *
FROM MEMBER;

SELECT ID  
FROM MEMBER  
WHERE ID  ='윤상필';

INSERT INTO MEMBER (id, pw, name, coupon, auth, adr, phone) VALUES ( '들어가줘', '1', 'ddd', 0, 0, '1', '1' );



