drop table menu
cascade constraints;

drop table member
cascade constraints;

drop table order_detail
cascade constraints;

CREATE TABLE MEMBER(
    NAME VARCHAR2(20) NOT NULL,
    ID VARCHAR2(10) PRIMARY KEY,
    PW VARCHAR2(20) NOT NULL,
    USEDCOUPON NUMBER(2),
    AUTH NUMBER(1) NOT NULL,
    ADR VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL
);

select * from member;

CREATE TABLE MENU(
    MENU_NAME VARCHAR2(30) PRIMARY KEY,
    PRICE NUMBER(5) NOT NULL,
    MENU_TYPE VARCHAR2(10) NOT NULL,
    DESCRIPTION VARCHAR2(1000) NOT NULL,
    AVG_RATE NUMBER(2)
);
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('진짜 매운 치킨', 12000, 'main','맛있다구요 !!',8);
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('덜 매운 치킨', 12000, 'main','맛있다구요 !!',2.3);
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('후라이드 치킨', 12000, 'main','맛있다구요 !!','5.2');
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('양념 치킨', 12000, 'main','맛있다구요 !!','5.2');
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('반반 치킨', 12000, 'main','맛있다구요 !!','5.2');
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('마늘 치킨', 12000, 'main','맛있다구요 !!','5.2');
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('간장 치킨', 12000, 'main','맛있다구요 !!','5.2');
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('감자튀김', 2000, 'side','맛있다구요 !!','5.2');
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('치즈스틱', 5000, 'side','맛있다구요 !!','5.2');
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('콜라', 2000, 'drink','맛있다구요 !!','5.2');
INSERT INTO MENU(MENU_NAME,PRICE, MENU_TYPE, DESCRIPTION, AVG_RATE)
VALUES ('사이다', 2000, 'drink','맛있다구요 !!','5.2');


SELECT * FROM MENU;

CREATE TABLE ORDER_DETAIL(
    ID VARCHAR2(10),
    MENU_NAME VARCHAR2(30),
    COUNT NUMBER(10) NOT NULL,
    BEV_COUPON NUMBER(3),
    ORDER_DATE DATE NOT NULL,
    REVIEW VARCHAR2(1000),
    SCORE NUMBER(5),
    CONSTRAINT FK_ID FOREIGN KEY(ID)
    REFERENCES MEMBER(ID),
    CONSTRAINT FK_MENU FOREIGN KEY(MENU_NAME)
    REFERENCES MENU(MENU_NAME)
);


SELECT * FROM ORDER_DETAIL;
