CREATE TABLE MEMBER(
    NAME VARCHAR2(20) NOT NULL,
    ID VARCHAR2(10) PRIMARY KEY,
    PW VARCHAR2(20) NOT NULL,
    COUPON NUMBER(1),
    AUTH NUMBER(1) NOT NULL,
    ADR VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL
);

CREATE TABLE MENU(
    MENU_NAME VARCHAR2(15) PRIMARY KEY,
    PRICE NUMBER(5) NOT NULL
);

DROP TABLE ORDER_DETAIL
DROP TABLE ORDER_DETAIL
CASCADE CONSTRAINTS;

CREATE TABLE ORDER_DETAIL(
    ID VARCHAR2(10),
    MENU_NAME VARCHAR2(15),
    COUNT1 NUMBER(10) NOT NULL,
    BEV_COUPON NUMBER(10),
    REVIEW VARCHAR2(1000),
    SCORE NUMBER(5)
);
SELECT *
FROM ORDER_DETAIL

INSERT INTO ORDER_DETAIL(ID, MENU_NAME, COUNT1, BEV_COUPON, REVIEW, SCORE) 
VALUES ('윤상', '후라', 1, 1, '짱짱', 1)

INSERT INTO MEMBER (id, pw, name, coupon, auth, adr, phone) 
VALUES ( '들어', '1', 'ddd', 0, 0, '1', '1' );

ALTER TABLE ORDER_DETAIL
ADD CONSTRAINT FK_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

CONSTRAINT MEMBER_ID 
FOREIGN KEY ID 
REFERENCES MEMBER ID


SELECT ID ,PW  FROM MEMBER  WHERE ID = '55' AND PW = '5' 

SELECT *
FROM MEMBER;

SELECT ID  
FROM MEMBER  
WHERE ID  ='윤상필';





