CREATE TABLE MEMBER(
    NAME VARCHAR2(20) NOT NULL,
    ID VARCHAR2(10) PRIMARY KEY,
    PW VARCHAR2(20) NOT NULL,
    COUPON NUMBER(1),
    AUTH NUMBER(1) NOT NULL,
    ADR VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL
);

CREATE TABLE MENU(
    MENU_NAME VARCHAR2(50) PRIMARY KEY,
    PRICE NUMBER(5) NOT NULL
);


CREATE TABLE ORDER_DETAIL(
    ID VARCHAR2(10),
    MENU_NAME VARCHAR2(50),
    COUNT NUMBER(10) NOT NULL,
    BEV_COUPON NUMBER(10),
    ORDER_DATE DATE NOT NULL,
    REVIEW VARCHAR2(1000),
    SCORE NUMBER(5),
    CONSTRAINT FK_ID FOREIGN KEY(ID)
    REFERENCES MEMBER(ID),
    CONSTRAINT FK_MENU FOREIGN KEY(MENU_NAME)
    REFERENCES MENU(MENU_NAME)
);


INSERT INTO MEMBER(NAME, ID, PW, COUPON, AUTH, ADR, PHONE)
VALUES('홍길동', 'HONG', '123', 0, 3, '경기도', '010-1111-2222');

INSERT INTO MEMBER(NAME, ID, PW, COUPON, AUTH, ADR, PHONE)
VALUES('일지매', 'ILL', '345', 2, 3, '부산', '010-3333-2222');

INSERT INTO MEMBER(NAME, ID, PW, COUPON, AUTH, ADR , PHONE)
VALUES('백승지', 'BAEK', '234', 1, 1, '서울', '010-2222-1111');


INSERT INTO ORDER_DETAIL(ID, MENU_NAME, COUNT, BEV_COUPON, ORDER_DATE, REVIEW, SCORE)
VALUES('HONG', '후라이드 치킨', 1 , 0 , SYSDATE , null, null);

INSERT INTO ORDER_DETAIL(ID, MENU_NAME, COUNT, BEV_COUPON, ORDER_DATE, REVIEW, SCORE)
VALUES('ILL', '양념 치킨', 2 , 1 , SYSDATE , null, null);

SELECT SYSDATE
FROM DUAL;


INSERT INTO MENU(MENU_NAME, PRICE)
VALUES('후라이드 치킨', 16000);

INSERT INTO MENU(MENU_NAME, PRICE)
VALUES('양념 치킨', 18000);

SELECT * FROM MEMBER;
SELECT * FROM MENU;
SELECT * FROM ORDER_DETAIL;

DROP TABLE ORDER_DETAIL
CASCADE CONSTRAINTS;




SELECT DISTINCT A.ORDER_DATE, A.MENU_NAME, A.COUNT, A.BEV_COUPON, B.PRICE
FROM ORDER_DETAIL A, MENU B
WHERE A.MENU_NAME = B.MENU_NAME;


