CREATE TABLE MEMBER(
	    NAME VARCHAR2(20) NOT NULL,
	    ID VARCHAR2(10) PRIMARY KEY,
	    PW VARCHAR2(20) NOT NULL,
	    COUPON NUMBER(1),
	    AUTH NUMBER(1) NOT NULL,
	    ADR VARCHAR2(30) NOT NULL,
	    PHONE VARCHAR2(20) NOT NULL
	);
	
	INSERT INTO MEMBER (NAME, ID, PW, COUPON, AUTH, ADR, PHONE)
	VALUES ('이도현','dh','123','1','3','서울','010-0000-0000');
	INSERT INTO MEMBER (NAME, ID, PW, COUPON, AUTH, ADR, PHONE)
	VALUES ('윤상필','sp','123','1','3','서울','010-0000-0000');
	INSERT INTO MEMBER (NAME, ID, PW, COUPON, AUTH, ADR, PHONE)
	VALUES ('백승지','sj','123','1','3','부천','010-0000-0000');
	INSERT INTO MEMBER (NAME, ID, PW, COUPON, AUTH, ADR, PHONE)
	VALUES ('김다슬','ds','123','1','3','김포','010-0000-0000');
	INSERT INTO MEMBER (NAME, ID, PW, COUPON, AUTH, ADR, PHONE)
	VALUES ('우진영','jy','123','1','3','포항','010-0000-0000');
	
	SELECT * FROM MEMBER;

	---------------------------------------------------------

	CREATE TABLE MENU(
	    MENU_NAME VARCHAR2(50) PRIMARY KEY,
	    PRICE NUMBER(5) NOT NULL
	);
	
	INSERT INTO MENU (MENU_NAME, PRICE)
	VALUES ('후라이드 치킨',12000);
	INSERT INTO MENU (MENU_NAME, PRICE)
	VALUES ('양념 치킨',12000);
	INSERT INTO MENU (MENU_NAME, PRICE)
	VALUES ('반반 치킨',12000);
	INSERT INTO MENU (MENU_NAME, PRICE)
	VALUES ('마늘 치킨',12000);
	INSERT INTO MENU (MENU_NAME, PRICE)
	VALUES ('간장 치킨',12000);
	INSERT INTO MENU (MENU_NAME, PRICE)
	VALUES ('콜라',12000);
	INSERT INTO MENU (MENU_NAME, PRICE)
	VALUES ('사이다',12000);

		SELECT * FROM MENU;
----------------------------------------------------

	CREATE TABLE ORDER_DETAIL(
	    ID VARCHAR2(10),
	    MENU_NAME VARCHAR2(15),
	    COUNTS NUMBER(10) NOT NULL,
	    BEV_COUPON NUMBER(10),
	    ORDER_DATE DATE NOT NULL,
	    REVIEW VARCHAR2(1000),
	    SCORE NUMBER(5),
	    CONSTRAINT FK_ID FOREIGN KEY(ID)
	    REFERENCES MEMBER(ID),
	    CONSTRAINT FK_MENU FOREIGN KEY(MENU_NAME)
	    REFERENCES MENU(MENU_NAME)
	);
	

	
	SELECT * FROM ORDER_DETAIL;